---
title: "Dual Y Axis"
author: "Zach"
date: 2020-10-22
output:
  github_document
---

A small demo of a dual y-axis, for showing multiple trends with dissimilar units at once. Adapted from [here](https://www.r-graph-gallery.com/line-chart-dual-Y-axis-ggplot2.html).

```{r setup}
library(tidyverse)

# Build dummy data
df_data <- data.frame(
  day = as.Date("2019-01-01") + 0:99,
  temperature = runif(100) + seq(1,100)^2.5 / 10000,
  price = runif(100) + seq(100,1)^1.5 / 10
)
```

```{r demo}
# Value used to transform the data
coeff <- 10

# A few constants
temperatureColor <- "#69b3a2"
priceColor <- rgb(0.2, 0.6, 0.9, 1)

ggplot(df_data, aes(x=day)) +

  geom_line( aes(y=temperature), size=2, color=temperatureColor) +
  geom_line( aes(y=price / coeff), size=2, color=priceColor) +

  scale_y_continuous(

    # Features of the first axis
    name = "Temperature (Celsius °)",

    # Add a second axis and specify its features
    sec.axis = sec_axis(~.*coeff, name="Price ($)")
  ) +

  theme_minimal() +

  theme(
    axis.title.y = element_text(color = temperatureColor, size=13),
    axis.title.y.right = element_text(color = priceColor, size=13)
  ) +

  ggtitle("Temperature down, price up")
ggsave("./dual-demo.png")
```
